export type OIDCWellKnown = {
  authorization_endpoint: string;
  backchannel_logout_session_supported: boolean;
  backchannel_logout_supported: boolean;
  claims_supported: string[];
  code_challenge_methods_supported: string[];
  device_authorization_endpoint: string;
  id_token_signing_alg_values_supported: string[];
  issuer: string;
  jwks_uri: string;
  mfa_challenge_endpoint: string;
  registration_endpoint: string;
  request_parameter_supported: boolean;
  request_uri_parameter_supported: boolean;
  response_modes_supported: string[];
  response_types_supported: string[];
  revocation_endpoint: string;
  scopes_supported: string[];
  subject_types_supported: string[];
  token_endpoint: string;
  token_endpoint_auth_methods_supported: string[];
  token_endpoint_auth_signing_alg_values_supported: string[];
  userinfo_endpoint: string;
};
